### ISSUE TITLE
Replace custom template with WP basic template files.

### ISSUE THREAD

**Issue by flangofas** [QoboLtd/Qobo-WP-Generic-Theme#13]
Replace page-homepage.php template file with the basic template files of Wordpress. 
- front-page.php

The front page template is loaded if a static front page is specified under Admin > Settings > Reading.
- home.php

The home page template is the front page by default. If you do not set WordPress to use a static front page, this template is used to show latest posts.

Source: https://developer.wordpress.org/themes/basics/template-files/#common-wordpress-template-files

**Comment by mamchenkov** [comment]
:+1:
