### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by flangofas** [QoboLtd/Qobo-WP-Generic-Theme#14]
- 404.php

The 404 template is used when WordPress cannot find a post, page, or other content that matches the visitor’s request.

Source: https://developer.wordpress.org/themes/basics/template-files/#common-wordpress-template-files

**Comment by mamchenkov** [comment]
@flangofas Yup, that would be awesome!  Especially if throw in some smart candy, like [Smart 404 pluging](https://wordpress.org/plugins/smart-404/installation/) or similar.

**Comment by flangofas** [comment]
https://github.com/QoboLtd/Qobo-WP-Generic-Theme/pull/15
This is done.
