### ISSUE TITLE
Missing Tag template - tag.php

### ISSUE THREAD

**Issue by flangofas** [QoboLtd/Qobo-WP-Generic-Theme#17]
REQUIRED: This theme doesn't seem to display tags. Modify it to display tags in appropriate locations.

See more - https://developer.wordpress.org/themes/basics/template-files/

**Comment by mamchenkov** [comment]
@flangofas not a bug ... In cases where tag.php is missing, WordPress falls back onto archive.php, and if that is missing, it falls into index.php.  Have a look at the template hierarchy chart:

https://developer.wordpress.org/files/2014/10/template-hierarchy.png

**Comment by flangofas** [comment]
@mamchenkov When I ran Theme check plugin I get the message in the description that why I reported it :smile:

**Comment by mamchenkov** [comment]
@flangofas ... and the crowd screams "Patch!!!" :)
